# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Otander
tagline:          'A Jekyll theme'
description:      'I build things by banging on a keyboard.'
url:              http://johnotander.com

author:
  name:           'John Otander'
  url:            https://twitter.com/4lpine
  email:          'johnotander@icloud.com'
  twitter:        '4lpine'
  github:         'johnotander'

paginate:         4

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/johnotander/johnotander.github.io
