# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Otander
tagline:          Ramblings
description:      'I build things by banging on a keyboard.'
baseurl:          http://johnotander.com/

author: 'John Otander'
email:  'johnotander@gmail.com'

paginate:         4

github:
  repo:           https://github.com/johnotander/johnotander.github.io
