# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Maid
tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/4lpine" target="_blank">@4lpine</a> and based on <a href="http://lanyon.getpoole.com">Lanyon</a> by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'John Otander'
  url:            https://twitter.com/4lpine
  email:          'johnotander@icloud.com'
  twitter:        '4lpine'
  github:         'johnotander'

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/johnotander/maid
